### ISSUE TITLE
Data submitted but not showing up

### ISSUE THREAD

**Issue by pzwsk** [GFDRR/open-risk-data-dashboard#145] opened 2018-08-03 07:09 UTC
Issue with this url, data has been submitted but record is not showing up https://index.opendri.org/contribute.html?ctr=AL&ds=Historical%20records%20of%20hazard%20events

Same issue with this one https://index.opendri.org/contribute.html?ctr=AL&ds=Flood%20hazard%20maps

For some reasons it considered there is no data submitted

**Comment by nastasi-oq** [comment] 2018-08-03 12:25
@pzwsk reopening the dataset it seems incomplete but I cannot reproduce the error inserting a new record (when I try to save it, correctly it alert me about the incompleteness of the form).
Could you give us more information about your client setup (Operative System, browser ... any other info that could be useful).
Thank you.

**Comment by nastasi-oq** [comment] 2018-09-12 07:44
@pzwsk any news ?

**Comment by pzwsk** [comment] 2018-09-18 06:35
No, need to ask again user.

**Comment by nastasi-oq** [comment] 2018-12-10 12:44
@pzwsk any news about this bug ? I suggest to close it and if it appear again we can reopen it.

**Closed** 2018-12-14 09:43 UTC
Labels: bug
